name: CmdSnooper
main: cmdsnooper\CmdSnooper
version: 2.0.0
api: 3.0.0-ALPHA11
author: Crafter20162017
description: §eSnoop on players

commands:
  snoop:
    description: Enter snoop mode
permissions:
   snoop.command:
    default: op
 
